# CBE 162 - Fall 2024 Lab 1: Introduction to Python Programming
Outline
* Installing Python and running Jupyter Notebooks
* Python basics: basic operations, lists, for/while loops, functions
* Numpy arrays
* Plotting using Matplotlib


This tutorial has been adapted from CBE143 at Berkeley (Spring 2021) and CS288 at Stanford (https://github.com/kuleshov/cs228-material)

## What are Jupyter Notebooks?
The Jupyter Notebook is an open-source application which may contain live/interactive code (including outputs and plots), rich text, equations, and visualizations.

## Installation
* This will depend on your operating system and whether you have Python already installed or not. Follow the instructions at: https://jupyter.readthedocs.io/en/latest/install/notebook-classic.html

* It is recommended that you use the Anaconda distribution. This will automatically install Python, Jupyter Notebook, and other commonly used packages. Note that we will be using Python 3 (select the most-recent version available through Anaconda).

* An alternative is to use Google Colaboratory (https://colab.research.google.com/notebooks/intro.ipynb). This does not require any configuration and gives you access to computing resources provided by Google. It is directly available in your Google Drive under New > More > Google Colaboratory.
  * Some keyboard shortcuts may be different than in Jupyter Notebooks, but the syntax and organization are exactly the same. You can even export Google Colaboratory files as Jupyter Notebooks (.ipynb) and run them on Jupyter (or vice versa).

## Intro to Jupyter Notebooks
* Notebooks are organized in **cells**. The text within
each cell will be interpreted based on the type of cell it is.
  * Code: Code cells will be executed by the python interpreter as python code. More information
on python can be found here: https://docs.python.org/3/library/index.html
  * Markdown: Markdown cells will be interpreted by Jupyter and formatted to text.
More information on markdown can be found here: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html

Some examples below:

This is a markdown/text cell.

In [2]:
print('This is a code cell')

This is a code cell


**Useful Shortcuts**
* `Enter` to go to edit-mode
* `Shift + Enter` to execute the highlighted cell(s) and highlight following cell
* In command-mode, `j` or `k` to navigate cells with your keyboard
* In command-mode, use `a` to create a cell above
* In command-mode, use `b` to create a cell below
* In command-mode, use `dd` to delete cell(s)
* Select a cell and press 'm' to make it a text cell
  
**Math Notation**  
You can write properly formatted math within Markdown cells using the `$` operators
like so:

This is an equation within a line $Y = \sum_{i=1}^N x_i^2$ of text.
This is an equation centered in a new line: $$Y = \sum_{i=1}^N x_i^2$$
The above equation comes from surrounding `Y = \sum_{i=1}^N x_i^2` with `$$` symbols, i.e., `$$Y = \sum_{i=1}^N x_i^2$$`. One can also align multiple equations using the `align` environment and the `&` character as
```
\begin{align}
Y & = (x+Z)^2
\\
Z & = Y+5x-\sqrt{2Y}
\end{align}
```
which yields
\begin{align}
Y &  = (x+Z)^2
\\
Z & = Y+5x-\sqrt{2Y}
\end{align}
Note how the equations align where the `&` symbol is placed.

The math is written according to $\LaTeX$ notation.

**Latex Notation**  
A very powerful document typesetting language utilized by scientists. More info
can be found here: https://www.overleaf.com/learn

Here are some quick tips:
* Use an underscore `_` character to denote a subcript, e.g. `$x_2$` = $x_2$
* Use a carot `^` character to denote a superscript, e.g. `$x^2$` = $x^2$
* Use brackets around superscript/subscript to do multiple character superscript/subscript, e.g. `$x^{1+2+3}$` = $x^{1+2+3}$
* Use a backslash character to denote symbols, e.g. `$\alpha$` = $\alpha$, `$\beta^2$` = $\beta^2$
* Some more useful symbols: `$\sum$` = $\sum$, `$\int$` = $\int$, `$\frac{1}{2}$` = $\frac{1}{2}$

Use latex for any equations you write to make them more legible!

Last tip, in the Jupyter toolbar above there is a "Kernel" tab. In that tab, there is an
option to "Restart Kernel and Run All Cells...". Use this feature to verify that your
notebook will work as expected from start to finish. Before submitting any assignments make
sure you run it through the "Restart Kernel and Run All Cells..." test. 


## Importing Libraries/Packages to Environment
* Unlike MATLAB, Python needs to know if it needs to access code that is not included in the Python standard library (https://docs.python.org/3/library/)
* One reason that Python is so versatile is that there exist libraries/packages for a vast array of different purposes. Finding the right one to use can be an art in itself!
* Use the `import` keyword to import libraries/packages using the syntax `import name_of_library *as* name_you_assign`. Some of the most-widely used libraries are given below:

In [3]:
import numpy as np              # Used for handling arrays/vectors/matrices
import matplotlib.pyplot as plt # Used for plotting
import pandas as pd             # Used for data

## Installing Libraries/Packages
* This will typically be outlined in the library documentation. Two of the most common ways are `!conda install library_name` and `!pip install library_name`. The `!` before the command tells the notebook to execute the cell as a shell command.
* Google Colaboratory already has most common libraries available

## General advice
In any programming language, Google is your best friend! More likely than not, someone will have had a similar issue with the one that you are trying to figure out, so a simple Google search will usually resolve the issue.

## Python Basics

### Basic data types

In [4]:
# Integers
a = 3
print(a, type(a))
print('-------------')

# Float
b = 3.0
print(b, type(b))
print('-------------')

# Strings
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, 'length =', len(hello))
print('-------------')

# Booleans
t = True
f = False
print(type(t))

3 <class 'int'>
-------------
3.0 <class 'float'>
-------------
hello length = 5
-------------
<class 'bool'>
False
True
False


### Basic Operations

In [8]:
x = 4
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation
print('-------------')

x += 1    # x = x+1 
print(x)
x *= 2    # x = x*2
print(x) 
print('-------------')

# Logic operations
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;
print('-------------')

# String concatenation
hw = hello + world
print(hw)
hw = hello + ' ' + world
print(hw)

# String formatting
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting, %s for string, %d for floats
print(hw12)

5
3
8
16
-------------
5
10
-------------
False
True
False
True
-------------
helloworld
hello world
hello world 12


## Lists
A list is used to store multiple objects. A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

**NOTE: Python begins indexing from 0!**

In [9]:
xs = [3, 1, 2, 5]   # Create a list using square brackets []
#Note it is not an array by default, e.g., like in MATLAB, although it contains only numbers here
print(type(xs))
print(xs[2])      # Indexing starts from 0, NOT 1!
print(xs[-1])     # Negative indices count from the end of the list

<class 'list'>
2
5


In [10]:
# Lists can contain elements of different types, e.g.,
xs[2] = 'foo'    
print(xs)

[3, 1, 'foo', 5]


In [11]:
# Add a new element to the end of the list
xs.append('bar') 
print(xs)  

# Remove and return the last element of the list
x = xs.pop()     
print(x, xs) 

[3, 1, 'foo', 5, 'bar']
bar [3, 1, 'foo', 5]


## Slicing

In [14]:
nums = range(5)      # range is a built-in function that creates a generator of integers
print(nums)          # prints a range generator
print(list(nums))    # Prints "[0, 1, 2, 3, 4]"
nums = list(nums)    # Convert range object to a list to perform list slicing
print(nums[2:4])     # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])      # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])      # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])       # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])     # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums = nums+[5, 6]   # Concatenate the two lists together
print(nums)
nums[2:4] = [-9, -8] # Assign a new sublist to a slice
print(nums)          # Prints "[0, 1, 8, 9, 4]"

range(0, 5)
[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, -9, -8, 4, 5, 6]


## For Loops
**Identation is important in Python!!**

Notice how the for loop does not have an end keyword.

In [15]:
colors = ['red', 'green', 'blue']
for name in colors:
  print(name)
# No end keyword!

red
green
blue


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [16]:
colors = ['red', 'green', 'blue']
for idx, name in enumerate(colors):
  print('#{}: {}'.format(idx+1, name)) #idx+1 because Python starts indexing at 0!

#1: red
#2: green
#3: blue


## While Loops
Loop until a condition is satisfied

In [17]:
# Initialize
i = 1

while i <=20:
  i *= 2
print(i)

32


## List Comprehensions
Consider the following code, which computes the square of each element in a list

In [18]:
nums = [0, 1, 2, 3, 4]
squares = [] #empty list
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


You can simplify the above using list comprehensions, i.e.,

In [19]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


You can also add conditions, e.g.,

In [20]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


## Functions
Python functions are defined using the `def` keyword. Similar to loops, identation is important.

In [21]:
def squared(x):
    xSquared = x**2
    return xSquared

sq = squared(5)
print(sq)

25


You can also define functions to take optional arguments by setting their default value when you define the function. If you do not pass that argument, then the default will be used. If you pass a different argument, then that will take the place of the default argument.

In [22]:
def hello(name, loud=False):
    if loud==True:
        print('HELLO, {}!'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello(name = 'Fred', loud = True)

Hello, Bob!
HELLO, FRED!


## Problems
Our labs will have problems/exercises for you to complete during our alotted time.

**Problem 1:** Create a function that computes the sum $\sum_{i=0}^N (a_i^2+b_i^2)$. Test your function for $a=\{1, 2, 3 \}$, $b=\{2, 3, 4\}$.

In [52]:
# a = [1, 2, 3]
# b = [2, 3, 4]

def sum_of_squares(a, b):
    res = 0
    for i in range(len(a)):
        res += (a[i] ** 2) + (b[i] ** 2)

    print("the answer is:", res)

sum_of_squares([1, 2, 3],[2, 3, 4])


the answer is: 43


**Problem 2:** Create a function that returns a list containing the Fibonacci series up to a given number $N>2$. Test your function for $N=10$. The $i^\text{th}$ term of the Fibonacci series is defined as $\{x_i : x_i = x_{i-2}+x_{i-1}\}$.

In [61]:
def fib(N):
    a, b = 0, 1
    count = 0 
    while count < N:
        count += 1 
        print(a, end=' ')
        a, b = b, a+b

fib(10)

0 1 1 2 3 5 8 13 21 34 

## Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To use Numpy, we first need to import the `numpy` package (we typically import all the libraries/packages that we need at the top of the notebook)

In [32]:
import numpy as np

### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers (i.e., starting at 0). The number of dimensions is the rank of the array. The shape of an array is a tuple of integers giving the size of the array along each dimension.

In [33]:
# Create a rank 1 array
a = np.array([1, 2, 3])
print('Type of a:', type(a))
print('Shape of a =', a.shape)
print('Some individual elements:', a[0], a[1], a[2])

# Change an element of the array
a[0] = 5                 
print('Modified array =', a)    
print('-------------')    

# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]]) 
print('Type of b:', type(b))
print('Shape of b =', b.shape)
print('Entire array =\n', b)
print('Some individual elements:', b[0,0], b[0,1], b[1,2])

Type of a: <class 'numpy.ndarray'>
Shape of a = (3,)
Some individual elements: 1 2 3
Modified array = [5 2 3]
-------------
Type of b: <class 'numpy.ndarray'>
Shape of b = (2, 3)
Entire array =
 [[1 2 3]
 [4 5 6]]
Some individual elements: 1 2 6


You can also define arrays of zeros, ones, empty arrrays, and more. Some examples are listed below.

In [34]:
 # Create an array of zeros
zeros = np.zeros((2,2)) 
print(zeros)
print('-------------')

# Create an array of ones
ones = np.ones((1,2))   
print(ones)
print('-------------')

# Create an array of a given constant
c = np.full((3,2), 7) 
print(c)
print('-------------')

# Create a 3x3 identity matrix
identity = np.eye(3)        
print(identity)
print('-------------')

# Create an array filled with random values
randomArray = np.random.random((2,2)) 
print(randomArray)

[[0. 0.]
 [0. 0.]]
-------------
[[1. 1.]]
-------------
[[7 7]
 [7 7]
 [7 7]]
-------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------
[[0.24003451 0.67661597]
 [0.78024366 0.00595247]]


### Array indexing
You can index a numpy array in several different ways. Numpy arrays can be sliced, similarrly to Python lists. However, since arrays may be multidimensional, you have to specify a slice for each dimension of the array.

In [38]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3]
print(b)

[[2 3]
 [6 7]]


**Caution:** A slice of an array is a view into the same data, so modifying it will modify the original array.

In [39]:
print(a[0, 1])  
b[0, 0] = 100    # b[0, 0] is the same piece of data as a[0, 1]
print(a)

2
[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array. Note that this is quite different from the way that MATLAB handles array slicing.



In [40]:
# Restore the original array a
a[0,1] = 2
print(a)
print('-------------')

# Extract the middle row using integers, slicing
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, 'Shape =', row_r1.shape) 
print(row_r2, 'Shape =', row_r2.shape)
print(row_r3, 'Shape =', row_r3.shape)
print('-------------')

# Similarly, for columns
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
col_r2 = a[:, [1]]
print(col_r1, '\nShape =', col_r1.shape)
print(col_r2, '\nShape =', col_r2.shape)
print(col_r2, '\nShape =', col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
[5 6 7 8] Shape = (4,)
[[5 6 7 8]] Shape = (1, 4)
[[5 6 7 8]] Shape = (1, 4)
-------------
[ 2  6 10] 
Shape = (3,)
[[ 2]
 [ 6]
 [10]] 
Shape = (3, 1)
[[ 2]
 [ 6]
 [10]] 
Shape = (3, 1)


Boolean array indexing: Frequently this type of indexing is used to select the elements of an array that satisfy some condition. For example,

In [41]:
# Define some arbitrary array
a = np.array([[1,2], [3, 4], [5, 6]])

boolIdx = (a > 2)  # Find the elements of a that are greater than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.
print(boolIdx)
print('-------------')

# To obtain the array of values greater than 2 we need to slice a with the indices obtained
aGreaterThan2 = a[boolIdx]
print(aGreaterThan2)
print('-------------')

# We can combine the two statements above as
aGreaterThan2 = a[a>2]
print(aGreaterThan2)

[[False False]
 [ True  True]
 [ True  True]]
-------------
[3 4 5 6]
-------------
[3 4 5 6]


### Data Types
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [42]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1.1, 2.6], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

print(x)
print(y)
print(z) # Note how the decimal points are discarded, 
         # since we specified the datatype to be integers!

int64 float64 int64
[1 2]
[1. 2.]
[1 2]


### Array Math
Basic mathematical functions operate elementwise on arrays.

In [43]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Addition
print(x + y)
print(np.add(x, y))
print('-------------')

# Subtraction
print(x - y)
print(np.subtract(x, y))
print('-------------')

# Product (Elementwise - NOT matrix multiplication)
print(x * y)
print(np.multiply(x, y))
print('-------------')

# Ratio
print(x / y)
print(np.divide(x, y))
print('-------------')

# Square Root
print(np.sqrt(x))
print('-------------')



[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
-------------
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
-------------
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
-------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
-------------
[[1.         1.41421356]
 [1.73205081 2.        ]]
-------------


Numpy also already includes many useful functions for performing computations on arrays. One of the most useful is the `sum` function.

In [44]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements

# Axis: the dimension across which you want to perform the operation
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


As we saw above, the `*` operator performs elementwise (rather than matrix) multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects.

In [45]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))
print('-------------')

# Matrix / vector product
print(x.dot(v))
print(np.dot(x, v))
print('-------------')

# Matrix / matrix product
print(x.dot(y))
print(np.dot(x, y))

219
219
-------------
[29. 67.]
[29. 67.]
-------------
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


Transposing and reshaping arrays

In [46]:
# Transpose
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)
print('-------------')

# Reshape
print(x.reshape(1, 4))
print(x.reshape(4,1))
print('-------------')

# Reshape using -1 as a dimension
print(x.reshape(1, -1))
print(x.reshape(-1, 1))
print('-------------')

# Reshape to a rank 1 array
y = x.reshape(-1,)
print(y.shape)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
-------------
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
-------------
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
-------------
(4,)


### Broadcasting
Broadcasting allows numpy to work with arrays of different shapes when performing operations. For example, we may want to use a smaller array multiple times to perform some operation on a larger array.

Suppose that we want to add a constant vector to each row of a matrix. We can do this in 3 ways:

In [47]:
# We will add the vector v to each row of the matrix x
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
# Initialize an empty matrix with the same shape as x. 
# Alternatively, one also initialize a matrix of zeros using np.zeros
y = np.empty_like(x)   

# Add the vector v to each row of the matrix x with an explicit loop
# This approach can be SLOW for large matrices!
for i in range(4):
    y[i, :] = x[i, :] + v

print('y =\n', y)
print('-------------')

# Stack 4 copies of v on top of each other
vv = np.tile(v, (4, 1))  
print('vv =\n',vv)
yy = x + vv
print('yy =\n', yy)
print('-------------')

# Using numpy broadcasting
yB = x + v
print('yB =\n', yB)

y =
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
-------------
vv =
 [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
yy =
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
-------------
yB =
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


`y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting. For more information about broadcasting, you can refer to the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Here are some applications of broadcasting:

In [48]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(np.reshape(v, (3, 1)) * w)
print('-------------')

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])  # x has shape (2,3)
v = np.array([1,2,3])             # v has shape (3,)
print(x + v)
print('-------------')

# Add a vector to each column of a matrix
x = np.array([[1,2,3], [4,5,6]])  # x has shape (2,3)
w = np.array([4,5])               # w has shape (2,)
# x.T has shape (3,2) and can be broadcast with w to yield a result
# with shape (3,2). Then we transpose the result to obtain a shape of
print((x.T + w).T)
print('-------------')

# Multiply a matrix by a constant
print(x * 2)


[[ 4  5]
 [ 8 10]
 [12 15]]
-------------
[[2 4 6]
 [5 7 9]]
-------------
[[ 5  6  7]
 [ 9 10 11]]
-------------
[[ 2  4  6]
 [ 8 10 12]]


## Plotting Graphs 
Matplotlib is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [49]:
import matplotlib.pyplot as plt



Here is an example of a figure containing subplots

In [1]:
# Compute the x and y coordinates for the points to be plotted
x = np.arange(0, 3 * np.pi, 0.1)
y1 = np.sin(x)
y2 = np.cos(x)
z = np.exp(x)

# Plot the points using matplotlib
plt.figure(dpi=100, figsize=(6, 4))
plt.subplot(211)
plt.plot(x, y1, label = 'sin(x)')
plt.plot(x, y2, label = 'cos(x)')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.subplot(212)
plt.plot(x,z)
plt.xlabel('x')
plt.ylabel('y')
plt.show()

NameError: name 'np' is not defined